### ISSUE TITLE
can u add viewmodel changer like masterlooser's?

### ISSUE THREAD

**Issue by shook1337** [T4zzuu/5shekelcheats#7]
https://imgur.com/a/67iPEEp

**Comment by ghost** [comment]
u add it? it's literally incrementing the fov value on up and down by (-) 10/15 ? each time

literally no idea what ur on about, dont expect people to just make things for u in an open source project 

stay cool, cat wit da glizzy

**Comment by shook1337** [comment]
this was made 12 days ago i was bored i have done coded the viewmodel changer myself

**Comment by ghost** [comment]
That's crazy
